# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs

executors:
  python-js:
    docker:
      - image: circleci/python:3.7-node-browsers
    working_directory: ~/project

jobs:
  install:
    executor: python-js
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ checksum "requirements.txt" }}-{{ checksum "yarn.lock" }}
      - run: python -m venv .venv
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt && yarn add now@latest
      - save_cache:
          key: deps-{{ checksum "requirements.txt" }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/project/.venv
            - ~/project/node_modules
      - persist_to_workspace:
          root: "~/"
          paths:
            - project/.venv
            - project/node_modules
            - project

  deploy:
    executor: python-js
    steps:
      - attach_workspace:
          at: "~/"
      - run:
          name: deploy_job
          command: |
            make prod
  preview:
    executor: python-js
    steps:
      - attach_workspace:
          at: "~/"
      - run:
          name: preview
          command: |
            make preview

workflows:
  version: 2
  deploy:
    jobs:
      - install
      - preview:
          requires:
            - install
          filters:
            branches:
              only:
                - develop
      - deploy:
          requires:
            - install
          filters:
            branches:
              only:
                - master

